name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify files
        run: |
          ls -la
          [ -f sources.list ] || { echo "sources.list missing"; exit 1; }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Image Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.image
          platforms: linux/amd64
          push: true
          tags: dorfnew/my-ai-app-image:latest

      - name: Build and push Video Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.video
          platforms: linux/amd64
          push: true
          tags: dorfnew/my-ai-app-video:latest

      - name: Build and push Audio Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.audio
          platforms: linux/amd64
          push: true
          tags: dorfnew/my-ai-app-audio:latest